In [9]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder
from sklearn.feature_extraction import FeatureHasher

df = pd.DataFrame({
    "color": ["Red","Green","Blue","Green","Red"],
    "Size": ["Small","Medium","Large","Medium","Small"],
    "City": ["Hyderabad","Delhi","Mumbai","Delhi","Chennai"],
    "Target": [10,20,15,25,12]
})
print(df)

   color    Size       City  Target
0    Red   Small  Hyderabad      10
1  Green  Medium      Delhi      20
2   Blue   Large     Mumbai      15
3  Green  Medium      Delhi      25
4    Red   Small    Chennai      12

In [11]:
from sklearn.preprocessing import LabelEncoder
df["color_Label"]=LabelEncoder().fit_transform(df["color"])
df[["color","color_Label"]]

   color  color_Label
0    Red            2
1  Green            1
2   Blue            0
3  Green            1
4    Red            2

In [12]:
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder(sparse_output=False)
encoded=encoder.fit_transform(df[["City"]])
encoded_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out(["City"]))
encoded_df

   City_Chennai  City_Delhi  City_Hyderabad  City_Mumbai
0           0.0         0.0             1.0          0.0
1           0.0         1.0             0.0          0.0
2           0.0         0.0             0.0          1.0
3           0.0         1.0             0.0          0.0
4           1.0         0.0             0.0          0.0

In [13]:
one_hot=pd.get_dummies(df["color"],prefix="color")
one_hot

   color_Blue  color_Green  color_Red
0       False        False       True
1       False         True      False
2        True        False      False
3       False         True      False
4       False        False       True

In [14]:
ohe=pd.get_dummies(df,columns=["color"])
print(ohe)

     Size       City  Target  color_Label  Size_Ordinal  City_Target_Enc  \
0   Small  Hyderabad      10            2           0.0             10.0
1  Medium      Delhi      20            1           1.0             22.5
2   Large     Mumbai      15            0           2.0             15.0
3  Medium      Delhi      25            1           1.0             22.5
4   Small    Chennai      12            2           0.0             12.0

   City_Freq_Enc  color_Blue  color_Green  color_Red
0              1       False        False       True
1              2       False         True      False
2              1        True        False      False
3              2       False         True      False
4              1       False        False       True

In [15]:
from sklearn.preprocessing import OrdinalEncoder
order=[["Small","Medium","Large"]]
df["Size_Ordinal"]=OrdinalEncoder(categories=order).fit_transform(df[["Size"]])

df[["Size","Size_Ordinal"]]

     Size  Size_Ordinal
0   Small           0.0
1  Medium           1.0
2   Large           2.0
3  Medium           1.0
4   Small           0.0

In [16]:
te=df.groupby("City")["Target"].mean()

df["City_Target_Enc"]=df["City"].map(te)
df[["City","City_Target_Enc"]]

        City  City_Target_Enc
0  Hyderabad             10.0
1      Delhi             22.5
2     Mumbai             15.0
3      Delhi             22.5
4    Chennai             12.0

In [17]:
freq=df["City"].value_counts()

df["City_Freq_Enc"]=df["City"].map(freq)
df[["City","City_Freq_Enc"]]

        City  City_Freq_Enc
0  Hyderabad              1
1      Delhi              2
2     Mumbai              1
3      Delhi              2
4    Chennai              1

In [19]:
from sklearn.feature_extraction import FeatureHasher
fh=FeatureHasher(n_features=4, input_type="string")
hashed = fh.transform([[city] for city in df["City"]])
hashed_df = pd.DataFrame(hashed.toarray())
hashed_df

     0    1    2    3
0 -1.0  0.0  0.0  0.0
1  0.0  0.0  0.0 -1.0
2  0.0  0.0 -1.0  0.0
3  0.0  0.0  0.0 -1.0
4  0.0  0.0  1.0  0.0